openapi: 3.0.1
info:
  title: InventoryAPI
  description: API Definition of InventoryAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/inventory
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /xml:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /{customerId}:
    delete:
      parameters:
      - name: customerId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
